Ex1 solution
GabrielInTheWorld/dance-management-app pull request #1
Opened 2022-03-23 08:53 UTC by luisa-beerboom

2022-03-23 13:01 UTC, GabrielInTheWorld requested changes

2022-03-23 13:01 UTC, GabrielInTheWorld commented on .vscode/settings.json
> +{
Please do not upload `.vscode/*` files

2022-03-23 13:01 UTC, GabrielInTheWorld commented on dist/server/server.js
> +"use strict";
Also ensure that the `dist/*` files won't be uploaded.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/data.ts
> +export class UserData {
Good abstraction! You could call it `UserRepository`.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/data.ts
> +  constructor() {
Please add a visibility modifier even if it's `public`

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +export class MapPersistor<V>{
Create an interface which share the functions a persistor will provide. Then implement it in the `MapPersistor` and define the type of your persistor in your repository as the interface.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +    persistData(toBePersisted: Map<number, V>){
Define always a return even if it's `void`.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +    }
Try to write a function in approximate 20 lines.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +                });
Write in a maximum depth of two blocks (meaning: no more than two if, for, try... nested blocks).

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +    }
In JS/TS you can write `private filePath: string` in the constructor. Then, the variable `filePath` is available in the whole class. Please also add the modifier `readonly` unless you want to change the variable's value.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +        let idCounter = 0;
Prefer `const` over `let` unless you want to change a variable's value.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/data.ts
> +  addUser(title: user.Title, firstName: string, lastName: string): Map<number, user.User> {
Do not return any other type than `void` if a function does not suggest this. `addUser` suggests only to add a user, not to get any data.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/data.ts
> +  changeUserData(id: number, title: user.Title, firstName: string, lastName: string): Map<number, user.User> {
Same as `addUser`.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/data.ts
> +  deleteUser(id: number): Map<number, user.User> {
Same as `addUser`.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/data.ts
> +  changeUserData(id: number, title: user.Title, firstName: string, lastName: string): Map<number, user.User> {
Besides, what is the difference between `UserData` and `User`? If there is no difference, than name it equally.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/data.ts
> +  addUser(title: user.Title, firstName: string, lastName: string): Map<number, user.User> {
It is better to accept zero or one arguments up to a maximum of two arguments. So, you should pass an object.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/user.ts
> +export function isSimpleUser (suspectedUser: any): suspectedUser is User {
What do you mean with `SimpleUser`? Is this a different object than `User`? If not, than name it just `isUser`.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/server.ts
> +
Remove unused functions.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/server.ts
> +    }
Nice implementation!

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/server.ts
> +    if (typeof request.body?.id === 'number' && isSimpleUser({title: request.body?.title, firstName: request.body?.firstName, lastName: request.body?.lastName })) {
You should pass only the `request.body` to ensure that the correct data came in.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/server.ts
> +        let usermap = users.changeUserData(request.body.id, request.body.title, request.body.firstName, request.body.lastName);
Remove unused variables.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/server.ts
> +})
Separate this into an own "service", like a `UserController`.

2022-03-23 13:01 UTC, GabrielInTheWorld commented on src/user.ts
> +}
It is good to create an interface to define interfaces between classes and services (and so on). Especially in TypeScript, interfaces are "syntactic sugar": They are going to be removed after compiled to JS. Therefore, you have two options: 
1. You can convert this interface to a class and let it "self-assign" the data
2. You can implement a "build"-function, which creates an instance of the `User`-interface

2022-03-23 14:49 UTC, luisa-beerboom commented on src/mappersistor.ts
> +        let idCounter = 0;
Both `users` and `idCounter` are variables that are changed later on, as long as there is a save-file, but I'll remember this for next time.

2022-03-23 14:52 UTC, luisa-beerboom commented on src/mappersistor.ts
> +                });
...which means that I should delegate the inner blocks to a new function, right?

2022-03-23 15:08 UTC, luisa-beerboom commented on src/mappersistor.ts
> +        let idCounter = 0;
...and at least `users` has to remain that way, as far as i see it

2022-03-23 15:24 UTC, luisa-beerboom commented on src/server.ts
> +})
which part? The entire request handling, or just the broadcasting-part?

2022-03-25 05:57 UTC, GabrielInTheWorld requested changes

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/controller.ts
> +    private users: userdata.UserRepository;
You can initialize your repo right here instead of in the constructor.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/controller.ts
> +import * as userdata from './data';
Please import always concrete files not just the whole directory.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on .gitignore
> +.vscode/
That is good. Now, you have to ensure, that those files really aren't going to publish on GitHub. Also, please prevent the "cache" (`.angular/cache`) to be published.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/controller.ts
> +        this.users = new userdata.UserRepository();
It is better to name a variable like its type or its designated use. In your is something like `userRepo` a good choice.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +    public async loadData(): Promise<[Map<number, V>, number]> {
It is better to work with objects/classes instead of simple arrays. In case of arrays, one has to know, what is `[0]`, what is `[1]`, ....

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +        let loadedData = await new Promise<string>((resolve, reject) => {
This should be a `const`.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/mappersistor.ts
> +                let loadedData = await this.actuallyLoadData();
This should be a `const`.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/user.ts
> +export interface IdentifiedUser {
You can extend by the `SimpleUser`.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/user.ts
> +export interface User {
You can extend by the `SimpleUser`.

2022-03-25 05:57 UTC, GabrielInTheWorld commented on src/user.ts
> +  return {title: prototype.title, firstName: prototype.firstName, lastName:prototype.lastName, joinedAt: Date.now()};
Good, but be careful: In JS/TS the word `prototype` has a meaningful role.

2022-03-25 14:25 UTC, GabrielInTheWorld requested changes
Please also rename your files accordingly to their most meaningful classes/tasks.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/user.ts
> +export type Title = typeof possibleTitles;
Adjust the type for `Title` and also adjust the "real" type of `possibleTitles` as discussed.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/controller.ts
> +            if (isSimpleUser(request.body)) {
Checking the correct type of a request's body should be done in a related repository.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/controller.ts
> +            if (isIdentifiedUser(request.body)) {
Same as above.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/controller.ts
> +            if (typeof request.body?.id === 'number') {
Same as above.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/data.ts
> +    this.users.set(this.idCounter, buildUser(info));
Before you insert into your database any data, you should ensure, that the data is correct/consistent.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/data.ts
> +    this.users.set(this.idCounter, buildUser(info));
Besides, it is a better style to throw an exception if incoming data do not match your expected structure.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/data.ts
> +      throw new Error("Data: Can't change nonexistant user.");
Very good handling! One hint: You can first check, if your map has not an entry indicated by `info.id` and if so, throw an exception. Using that way, your code moves one layer higher.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/data.ts
> +      throw new Error("Data: Can't delete nonexistant user.");
Same as above.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/persistor.ts
> +export interface ReposSetupData<V>{
Your persistor shouldn't know anything about your repositories. So, change this name.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/user.ts
> +  return {title: info.title, firstName: info.firstName, lastName: info.lastName, joinedAt: Date.now()};
Using your above "guards", you always know that your passed data is from type `SimpleUser`. So, you can just copy every date from your passed data into a new object.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/user.ts
> +export function changeUser(newData: SimpleUser, toBeChanged: User): User{
Same as above.

2022-03-25 14:25 UTC, GabrielInTheWorld commented on src/controller.ts
> +    public constructor(private readonly app: Express, private broadcast: { (dataToBroadcast: string): void }) {
Maybe you should extract the function body of your request handlers into an own function to prevent overloading the constructor.

2022-03-29 08:36 UTC, GabrielInTheWorld requested changes
One thing, then it is fine.

2022-03-29 08:36 UTC, GabrielInTheWorld commented on src/controller.ts
> +    private handleGetAll(request: Request, response: Response, next: NextFunction) {
You are missing the `return` values

2022-03-30 06:50 UTC, GabrielInTheWorld submitted a review, later dismissed
Now, you have to squash these commits and push the result. Then, it can be merged into main.

2022-03-30 07:22 UTC, GabrielInTheWorld approved these changes

2022-03-30 07:22 UTC, merged